In [2]:
import torch
import numpy as np

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_arr = np.array(data)
x_arr = torch.from_numpy(np_arr)
x_arr

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.5107, 0.2215],
        [0.6338, 0.2496]])

In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.8826, 0.4474, 0.7327],
        [0.7813, 0.3561, 0.1947]])

In [7]:
t = torch.rand((3,4), device='cuda')
[t.shape, t.dtype, t.device]

[torch.Size([3, 4]), torch.float32, device(type='cuda', index=0)]

### Operations

In [8]:
t = torch.ones(4,4)
t[0]

tensor([1., 1., 1., 1.])

In [9]:
t[:, 0]

tensor([1., 1., 1., 1.])

In [10]:
t[:, 1] = 0
t

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [11]:
torch.cat([t, t], dim=1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])

In [12]:
t.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
t @ t.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [14]:
t.matmul(t.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [15]:
y = torch.zeros_like(t)
torch.matmul(t, t.T, out=y)
y

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [16]:
t.sum()

tensor(12.)

In [17]:
t.sum().item()

12.0

In [18]:
t.add_(2)

tensor([[3., 2., 3., 3.],
        [3., 2., 3., 3.],
        [3., 2., 3., 3.],
        [3., 2., 3., 3.]])

In [19]:
t

tensor([[3., 2., 3., 3.],
        [3., 2., 3., 3.],
        [3., 2., 3., 3.],
        [3., 2., 3., 3.]])

### Numpy bridge

In [21]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [23]:
nt = t.numpy()
nt

array([1., 1., 1., 1., 1.], dtype=float32)

In [24]:
t.add_(5)
t

tensor([6., 6., 6., 6., 6.])

In [25]:
nt

array([6., 6., 6., 6., 6.], dtype=float32)

In [27]:
ntt = np.ones(5)
ntt

array([1., 1., 1., 1., 1.])

In [28]:
tt = torch.from_numpy(ntt)
tt

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)